version: '3.4'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always    
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    restart: always             # run as a service

  app: &app_base
    image: app:latest
    build:
      context: .
    environment:
      - SECRET_KEY_BASE=27d95944e1362efa96aebab79c640d1e68b9c54acee0f20c544584896a2ff8c8b33299ccec52646f0181519c37f165034063ce79791e5112f8ed8e30865ffbd9
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - APP_ADMIN_EMAIL=admin@example.org
      - APP_ADMIN_PASSWORD=secret
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - ./:/app
    command: bundle exec rails s -b 0.0.0.0
